# Generated by Django 5.1.4 on 2024-12-20 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_alter_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('parent_category', models.CharField(choices=[('Gaming Consoles', 'Gaming Consoles'), ('PC Gaming', 'PC Gaming'), ('Gaming Accessories', 'Gaming Accessories'), ('Games', 'Games'), ('In-Game Items', 'In-Game Items'), ('Gaming Peripherals', 'Gaming Peripherals'), ('Streaming Equipment', 'Streaming Equipment'), ('Merchandise', 'Merchandise'), ('Mobile Gaming', 'Mobile Gaming'), ('Gaming Subscriptions', 'Gaming Subscriptions'), ('Board and Card Games', 'Board and Card Games'), ('others', 'others')], max_length=255)),
                ('sub_category', models.CharField(choices=[('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Retro Consoles', 'Retro Consoles'), ('Handheld Consoles', 'Handheld Consoles'), ('Pre-built Gaming PCs', 'Pre-built Gaming PCs'), ('Gaming Laptops', 'Gaming Laptops'), ('Graphics Cards (GPUs)', 'Graphics Cards (GPUs)'), ('Processors (CPUs)', 'Processors (CPUs)'), ('Cooling Systems', 'Cooling Systems'), ('Controllers', 'Controllers'), ('Gaming Mice', 'Gaming Mice'), ('Keyboards', 'Keyboards'), ('Headsets', 'Headsets'), ('Gaming Chairs', 'Gaming Chairs'), ('VR Accessories', 'VR Accessories'), ('Action', 'Action'), ('Role-Playing Games (RPG)', 'Role-Playing Games (RPG)'), ('Sports', 'Sports'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Indie', 'Indie'), ('VR Games', 'VR Games'), ('Virtual Currencies', 'Virtual Currencies'), ('Skins', 'Skins'), ('Weapons', 'Weapons'), ('Characters', 'Characters'), ('Bundles', 'Bundles'), ('Monitors', 'Monitors'), ('Speakers', 'Speakers'), ('Microphones', 'Microphones'), ('Mouse Pads', 'Mouse Pads'), ('External Storage', 'External Storage'), ('Capture Cards', 'Capture Cards'), ('Lighting', 'Lighting'), ('Streaming Microphones', 'Streaming Microphones'), ('Camera/Facecam', 'Camera/Facecam'), ('Apparel', 'Apparel (T-Shirts, Hoodies, etc.)'), ('Action Figures', 'Action Figures'), ('Posters', 'Posters'), ('Collectibles', 'Collectibles'), ('Mobile Controllers', 'Mobile Controllers'), ('Gaming Phones', 'Gaming Phones'), ('Accessories', 'Accessories (Stands, Cooling Pads, etc.)'), ('Xbox Game Pass', 'Xbox Game Pass'), ('PlayStation Plus', 'PlayStation Plus'), ('Online Memberships', 'Online Memberships'), ('Tabletop RPGs', 'Tabletop RPGs'), ('Strategy Board Games', 'Strategy Board Games'), ('Card Games', 'Card Games'), ('Party Games', 'Party Games'), ('others', 'others')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
